package:
    name: odlpp
    version: "0.2.0"

source:
    git_url: https://github.com/odlgroup/odlpp.git
    git_rev: plugin_build_test
    # git_rev: v0.2.3

build:
    script_env:
        - CUDA_ROOT
        - CUDA_COMPUTE

requirements:
    build:
        - python
        - nomkl
        - setuptools
        - numpy >=1.9
        - future >=0.14
        - gcc <5    # [linux]
        - llvm      # [osx]
        - boost
        - odl
    run:
        - nomkl
        - python
        - numpy >=1.9
        - future >=0.14
        - boost
        - odl

test:
    imports:
        - odlpp

    requires:
        - pytest

about:
    home: https://github.com/odlgroup/odlpp
    license: GPLv3+
    license_file: LICENSE
    summary: ""

extra:
    maintainers:
        - Jonas Adler (@adler-j)
        - Holger Kohr (@kohr-h)


